# Generated by Django 4.2.1 on 2023-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("SOFT", "SOFT"), ("HARD", "HARD")], max_length=8
            ),
        ),
    ]
