# Generated by Django 4.2.1 on 2023-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="type_session",
        ),
    ]
